### ISSUE TITLE
Server kicks me while trying to get through a nectere portal

### ISSUE THREAD

**Issue by Strumero** [Heart-of-the-Machine/heart-of-the-machine#2] opened 2020-07-11 19:18 UTC
[ErrorLog.txt](https://github.com/Heart-of-the-Machine/heart-of-the-machine/files/4907498/ErrorLog.txt)

**Comment by meelock** [comment] 2020-07-12 01:09
Please upload a full log from the logs folder in your minecraft server folder.
Thanks!

**Comment by Kneelawk** [comment] 2020-07-12 01:23
This is caused by the server missing the Nectere dimension when the player tries to teleport to it. The previous version of Heart of the Machine had an issue where it would not create the Nectere dimension on dedicated servers, though this can also happen if you added Heart of the Machine after creating the world. This issue has been fixed, but in order to force the creation of the Nectere dimension on your server for a world that doesn't have it already, you just need to create a file named `force-hotm` in the same directory as the server.jar and restart the server.

**Comment by Kneelawk** [comment] 2020-07-12 01:24
However, I should make it so that attempting to teleport in a server that is missing the Nectere dimension will just send you a chat message instead of kicking you.

**Comment by Kneelawk** [comment] 2020-07-12 03:17
Currently the quick fix for dedicated servers is to add a file named `force-hotm` in the same directory as the server's server.jar.

I feel this is a bit of a hack and there needs to be a better way to configure retroactively adding the Nectere dimension to a world.

**Comment by Kneelawk** [comment] 2020-07-12 03:53
I am closing this issue because the crash and kick are technically fixed by 6046515 which is a part of the 0.1.2 beta release [available on CurseForge](https://www.curseforge.com/minecraft/mc-mods/heart-of-the-machine/files/3002620). I will be continuing discussion of the retro-generation configuration in a separate issue: #3.

**Closed by Kneelawk** 2020-07-12 03:53 UTC
Labels: bug
